//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Caso1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CasoEstudioMNEntities : DbContext
    {
        public CasoEstudioMNEntities()
            : base("name=CasoEstudioMNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<TiposCursos> TiposCursos { get; set; }
        public virtual DbSet<Consultas> Consultas { get; set; }
    
        public virtual int RegistrarMatricula(string nombre, Nullable<decimal> monto, Nullable<int> tipoCurso)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var tipoCursoParameter = tipoCurso.HasValue ?
                new ObjectParameter("TipoCurso", tipoCurso) :
                new ObjectParameter("TipoCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarMatricula", nombreParameter, montoParameter, tipoCursoParameter);
        }
    
        public virtual int RegistrarMatriculaV2(string nombre, Nullable<decimal> monto, Nullable<int> tipoCurso)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var tipoCursoParameter = tipoCurso.HasValue ?
                new ObjectParameter("TipoCurso", tipoCurso) :
                new ObjectParameter("TipoCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarMatriculaV2", nombreParameter, montoParameter, tipoCursoParameter);
        }
    }
}
